source = ./hyprland/theme.conf
source = ./hyprland/color.conf
source = ./binds.conf
source = ./rules.conf
source = ./windowrule.conf
source = ./monitors.conf
source = ./autostart.conf
source = ./env.conf

input {
    kb_layout = de
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    repeat_rate = 25
    repeat_delay = 300

    follow_mouse = 1

    sensitivity = 0 
    touchpad {
        natural_scroll = false
    }
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
