general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep-cmd = hyprctl dispatch dpms on && sleep 2 && hyprctl reload
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session && sleep 1 && systemctl suspend
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session && sleep 1 && systemctl suspend 
    on-resume = hyprctl dispath dpms eDP-1 on && hyprctl reload
}
